services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MODE=${MODE}
        - BASE_URL=${BASE_URL}
    image: web-pokedex:latest
    container_name: web-pokedex
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped