services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # Mantemos apenas o MODE como arg se o seu build precisar dele
      args:
        - MODE=${MODE}
    image: web-pokedex:latest
    container_name: web-pokedex
    ports:
      - "4000:4000"
    env_file:
      - .env.production.local
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/api/auth/providers"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s